// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buku_rumpin.DbContexts;

namespace buku_rumpin.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20230824102012_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("buku_rumpin.DTOs.CBukuDTO", b =>
                {
                    b.Property<Guid>("buku_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("bahasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("ed_cet")
                        .HasColumnType("TEXT");

                    b.Property<string>("id_lama")
                        .HasColumnType("TEXT");

                    b.Property<string>("isbn_issn")
                        .HasColumnType("TEXT");

                    b.Property<string>("judul")
                        .HasColumnType("TEXT");

                    b.Property<int>("kategori")
                        .HasColumnType("INTEGER");

                    b.Property<string>("keterangan")
                        .HasColumnType("TEXT");

                    b.Property<string>("penerbit")
                        .HasColumnType("TEXT");

                    b.Property<string>("penulis")
                        .HasColumnType("TEXT");

                    b.Property<int>("tahun_terbit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tempat_terbit")
                        .HasColumnType("TEXT");

                    b.Property<string>("uri_gambar")
                        .HasColumnType("TEXT");

                    b.HasKey("buku_id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
